name: 'Install Qt Creator development files'
description: 'Installs Qt Creator and its _dev packages'
author: 'The Qt Company'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'archive'
  color: 'green'

# Define your inputs here.
inputs:
  version:
    description: 'The version to install'
    required: true
    default: '14.0.0'
  unzip-to:
    description: 'Where to unzip the Qt Creator files to'
    required: true
    default: 'qt-creator'

# Define your outputs here.
outputs:
  path:
    description: 'Path to the extracted files.'

runs:
  using: node20
  main: dist/index.js
